name: Deploy to Pantheon

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4' # Adjust this to match your site's PHP version

    - name: Install Terminus
      run: |
        curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar
        php installer.phar install
        export PATH="$HOME/terminus/bin:$PATH"

    - name: Authenticate Terminus
      run: terminus auth:login --machine-token=${{ secrets.PANTHEON_MACHINE_TOKEN }}

    - name: Set Pantheon Connection to Git
      run: terminus connection:set ${{ secrets.PANTHEON_SITE_NAME }}.dev git

    - name: Deploy code to Pantheon
      run: |
        git remote add pantheon ssh://codeserver.dev.${{ secrets.PANTHEON_SITE_UUID }}@codeserver.dev.${{ secrets.PANTHEON_SITE_UUID }}.drush.in:2222/~/repository.git
        git push -f pantheon main

    - name: Clear Pantheon cache
      run: terminus env:clear-cache ${{ secrets.PANTHEON_SITE_NAME }}.dev