name: Deploy to Pantheon

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PANTHEON_SSH_PRIVATE_KEY }}

      - name: Add Pantheon to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 
codeserver.dev.81db7050-1ff8-48c7-83fe-2f8224d8e014.drush.in >> 
~/.ssh/known_hosts

      - name: Add Pantheon remote
        run: git remote add pantheon ${{ secrets.PANTHEON_GIT_URL }}

      - name: Push to Pantheon
        run: git push -f pantheon main
