name: Deploy to Pantheon

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Terminus
        run: |
          wget 
https://github.com/pantheon-systems/terminus/releases/download/3.0.4/terminus.phar
          chmod +x terminus.phar
          sudo mv terminus.phar /usr/local/bin/terminus

      - name: Authenticate with Pantheon
        env:
          TERMINUS_HIDE_UPDATE_MESSAGE: 1
        run: terminus auth:login --machine-token=${{ 
secrets.PANTHEON_MACHINE_TOKEN }}

      - name: Clone Pantheon repository
        run: |
          git clone $(terminus connection:info ${{ secrets.PANTHEON_SITE_NAME 
}}.dev --field=git_url) pantheon
          rsync -a --exclude='.git' --delete . pantheon/
          cd pantheon
          git add .
          git commit -m "Deploy from GitHub Actions"
          git push origin master

